name: Cypress Tests

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install npm dependencies and cache them
      - name: Install Dependencies
        run: npm install

      # Build the project before running tests
      - name: Build
        run: npm run build

      # Start the application before running tests
      - name: Start Application
        run: npm start
        background: true  # Run in the background to keep the workflow going

      # Run Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
